# Generated by Django 5.2.6 on 2025-10-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_student_accommodation_alter_student_avg_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_acload',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
